version: '3.9'

services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=needlehack
      - MONGO_INITDB_ROOT_USERNAME=ivangrod
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3t
