services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=needlehack
      - MONGO_INITDB_ROOT_USERNAME=ivangrod
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3t
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ivangrod
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: needlehack
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Connection pooling
#  pgbouncer:
#    image: edoburu/pgbouncer
#    environment:
#      - DB_USER=ivangrod
#      - DB_PASSWORD=s3cr3t
#      - DB_HOST=local_pgdb
#      - DB_NAME=needlehack
#      - AUTH_TYPE=scram-sha-256
#      - POOL_MODE=transaction
#      - ADMIN_USERS=postgres,ivangrod
#    volumes:
#      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
#    ports:
#      - "5432:5432"
#    depends_on:
#      - db

volumes:
  local_pgdata:
  pgadmin_data:
  mongo_data:
