spring:
  data:
    mongodb:
      database: needlehack
      authentication-database: admin
      username: ivangrod
      password: s3cr3t
    jpa:
      repositories:
        enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/needlehack
    username: ivangrod
    password: s3cr3t
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
